import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/components/Navbar";
import MainOVerlay from "@/components/MainOVerlay";
import Providers from "../providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const tuskerGrotesk = localFont({
  src: [
    {
      path: "../../public/fonts/tusker-grotesk/TuskerGrotesk-2500Medium.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/tusker-grotesk/TuskerGrotesk-4600Semibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/tusker-grotesk/TuskerGrotesk-4800Super.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--tusker-grotesk",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-sans ${tuskerGrotesk.variable}`}>
        <Providers>
          <Navbar />
          <MainOVerlay />
          {children}
        </Providers>
      </body>
    </html>
  );
}
